### ISSUE TITLE
System Setup Section missing?, requirements.txt not present, would be nice to have :) 

### ISSUE THREAD

**Issue by federico22285** [LiuYuancheng/Py_PLC_Honey_Pot#1]
Hello, 

There is no System Setup, the link redirects to the main github repo?, is this correct? also there is no requirements file. 

Many thanks, 
All the best

**Comment by LiuYuancheng** [comment]
> Hello,
> 
> There is no System Setup, the link redirects to the main github repo?, is this correct? also there is no requirements file.
> 
> Many thanks, All the best

Thanks for your comments. The project document is still under development, the setup section and the requirements.txt are added in the current version. For deploying the system, please check the user manual deployment section: 
https://github.com/LiuYuancheng/Py_PLC_Honey_Pot/blob/main/UserManual.md
