### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by dzcontrol** [LiuYuancheng/Py_PLC_Honey_Pot#2]
Hello ! thanks for this great project.

But seems like the index.html is missing in the honeypotMonitor template directory.

Thank you

**Comment by LiuYuancheng** [comment]
Hi dzcontrol, Thanks for pointing out, the missed file is added.

**Comment by dzcontrol** [comment]
Thanks for your reactivity @LiuYuancheng

Best Regards.
